export const EVENT_PHASE = {
  COMMERCIAL: "COMMERCIAL",
  OPERATIONAL: "OPERATIONAL",
  TERMINAL: "TERMINAL",
} as const;

export type EventPhase = (typeof EVENT_PHASE)[keyof typeof EVENT_PHASE];

export const EVENT_STATUS = {
  INQUIRY: "INQUIRY",
  FOLLOW_UP: "FOLLOW_UP",
  NO_RESPONSE: "NO_RESPONSE",
  QUOTING: "QUOTING",
  QUOTE_SENT: "QUOTE_SENT",
  QUOTED_NO_DATES: "QUOTED_NO_DATES",
  APPROVED: "APPROVED",
  LOST: "LOST",
  RESERVED: "RESERVED",
  DELIVERED: "DELIVERED",
  PICKED_UP: "PICKED_UP",
  INSPECTION_PENDING: "INSPECTION_PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export type EventStatusCode = (typeof EVENT_STATUS)[keyof typeof EVENT_STATUS];

export const EVENT_PRIORITY = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
} as const;

export const COMMERCIAL_STATUS_CODES: EventStatusCode[] = [
  EVENT_STATUS.INQUIRY,
  EVENT_STATUS.FOLLOW_UP,
  EVENT_STATUS.NO_RESPONSE,
  EVENT_STATUS.QUOTING,
  EVENT_STATUS.QUOTE_SENT,
  EVENT_STATUS.QUOTED_NO_DATES,
  EVENT_STATUS.APPROVED,
];

export const OPERATIONAL_STATUS_CODES: EventStatusCode[] = [
  EVENT_STATUS.RESERVED,
  EVENT_STATUS.DELIVERED,
  EVENT_STATUS.PICKED_UP,
  EVENT_STATUS.INSPECTION_PENDING,
];

export const TERMINAL_STATUS_CODES: EventStatusCode[] = [
  EVENT_STATUS.LOST,
  EVENT_STATUS.COMPLETED,
  EVENT_STATUS.CANCELLED,
];
