export const PRODUCT_CATEGORY = {
  TABLE_LINENS: "TABLE_LINENS",
  CHAIR_COVERS: "CHAIR_COVERS",
  CHAIRS: "CHAIRS",
  TABLES: "TABLES",
  DECORATION: "DECORATION",
  ACCESSORIES: "ACCESSORIES",
  OTHER: "OTHER",
} as const;

export const PRODUCT_TRACKING_TYPE = {
  QUANTITY: "QUANTITY",
  ASSET: "ASSET",
} as const;

export const PRODUCT_TYPE = {
  SIMPLE: "SIMPLE",
  BUNDLE: "BUNDLE",
} as const;

export const PRODUCT_PRICE_TYPE = {
  RENTAL: "RENTAL",
  SALE: "SALE",
} as const;

export const PRODUCT_COMBOBOX_PAGE_SIZE = 10;
export const PRODUCT_LIST_PAGE_SIZE = 20;
export const PRODUCT_SEARCH_DEBOUNCE_MS = 300;
