export const QUOTE_STATUS = {
  DRAFT: "DRAFT",
  SENT: "SENT",
  CUSTOMER_APPROVED: "CUSTOMER_APPROVED",
  PENDING_AVAILABILITY: "PENDING_AVAILABILITY",
  CONVERTED: "CONVERTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
} as const;

export const QUOTE_LINE_TYPE = {
  RENTAL: "RENTAL",
  SALE: "SALE",
  SERVICE: "SERVICE",
} as const;

export const DISCOUNT_TYPE = {
  PERCENTAGE: "PERCENTAGE",
  FIXED: "FIXED",
} as const;

export const DEFAULT_TAX_CODE = "IVA_13";
